services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    ports:
      - "8080:8080"
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [start-dev]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
