spring:
    application:
        name: taskflow
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://taskflow-db:5432/taskflow
        username: taskflow
        password: taskflow
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:7080/realms/taskflow
                    jwk-set-uri: http://keycloak:8080/realms/taskflow/protocol/openid-connect/certs